# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: us-east-1 

      - name: Invoke Lambda
        run: | 
          response=$(aws lambda invoke \
            --function-name flyctl_get_deploy_token \
            --cli-binary-format raw-in-base64-out \
            response.json)
          TOKEN=$(jq -r .body response.json)
          echo FLY_API_TOKEN=$TOKEN >> $GITHUB_ENV

      - name: Deploy Server
        run: flyctl deploy --remote-only
        env: 
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}

    
    
