# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: print github oidc token claims
        run: | 
          echo "Requesting github oidc token"
          TOKEN=$(curl -sH "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          echo "Token: $TOKEN" 

          echo "Decoded JWT claims:"
          echo "$TOKEN" | jq -r '.value' | cut -d '.' -f2 | base64 -d | jq .

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: us-east-1 

      - name: Invoke Lambda
        run: | 
          response=$(aws lambda invoke \
            --function-name flyctl_get_deploy_token \
            --cli-binary-format raw-in-base64-out \
            response.json)
          echo "Raw response from AWS CLI:"
          echo "$response"
      
          echo "Lambda function output:"
          cat response.json

    
    
